// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: cmd/cloudwegodemo/internal/config/config.proto

package config

import (
	server "cloudwegodemo/cmd/cloudwegodemo/internal/server"
	mysql "cloudwegodemo/pkg/database/mysql"
	redis "cloudwegodemo/pkg/database/redis"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Config struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Server *Server `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
}

func (x *Config) Reset() {
	*x = Config{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_cloudwegodemo_internal_config_config_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_cloudwegodemo_internal_config_config_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_cmd_cloudwegodemo_internal_config_config_proto_rawDescGZIP(), []int{0}
}

func (x *Config) GetServer() *Server {
	if x != nil {
		return x.Server
	}
	return nil
}

type Server struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Http     *server.HTTPServer `protobuf:"bytes,1,opt,name=http,proto3" json:"http,omitempty"`
	Rpc      *server.RPCServer  `protobuf:"bytes,2,opt,name=rpc,proto3" json:"rpc,omitempty"`
	Database *DataBase          `protobuf:"bytes,3,opt,name=database,proto3" json:"database,omitempty"`
}

func (x *Server) Reset() {
	*x = Server{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_cloudwegodemo_internal_config_config_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Server) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server) ProtoMessage() {}

func (x *Server) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_cloudwegodemo_internal_config_config_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server.ProtoReflect.Descriptor instead.
func (*Server) Descriptor() ([]byte, []int) {
	return file_cmd_cloudwegodemo_internal_config_config_proto_rawDescGZIP(), []int{1}
}

func (x *Server) GetHttp() *server.HTTPServer {
	if x != nil {
		return x.Http
	}
	return nil
}

func (x *Server) GetRpc() *server.RPCServer {
	if x != nil {
		return x.Rpc
	}
	return nil
}

func (x *Server) GetDatabase() *DataBase {
	if x != nil {
		return x.Database
	}
	return nil
}

type DataBase struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mysql *mysql.Option `protobuf:"bytes,1,opt,name=mysql,proto3" json:"mysql,omitempty"`
	Redis *redis.Option `protobuf:"bytes,2,opt,name=redis,proto3" json:"redis,omitempty"`
}

func (x *DataBase) Reset() {
	*x = DataBase{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_cloudwegodemo_internal_config_config_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataBase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataBase) ProtoMessage() {}

func (x *DataBase) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_cloudwegodemo_internal_config_config_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataBase.ProtoReflect.Descriptor instead.
func (*DataBase) Descriptor() ([]byte, []int) {
	return file_cmd_cloudwegodemo_internal_config_config_proto_rawDescGZIP(), []int{2}
}

func (x *DataBase) GetMysql() *mysql.Option {
	if x != nil {
		return x.Mysql
	}
	return nil
}

func (x *DataBase) GetRedis() *redis.Option {
	if x != nil {
		return x.Redis
	}
	return nil
}

var File_cmd_cloudwegodemo_internal_config_config_proto protoreflect.FileDescriptor

var file_cmd_cloudwegodemo_internal_config_config_proto_rawDesc = []byte{
	0x0a, 0x2e, 0x63, 0x6d, 0x64, 0x2f, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x77, 0x65, 0x67, 0x6f, 0x64,
	0x65, 0x6d, 0x6f, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x63, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x16, 0x63, 0x6d, 0x64, 0x2e, 0x68, 0x7a, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61,
	0x6c, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x1a, 0x2e, 0x63, 0x6d, 0x64, 0x2f, 0x63, 0x6c,
	0x6f, 0x75, 0x64, 0x77, 0x65, 0x67, 0x6f, 0x64, 0x65, 0x6d, 0x6f, 0x2f, 0x69, 0x6e, 0x74, 0x65,
	0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1e, 0x70, 0x6b, 0x67, 0x2f, 0x64, 0x61,
	0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x2f, 0x6d, 0x79, 0x73, 0x71, 0x6c, 0x2f, 0x6d, 0x79, 0x73,
	0x71, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1e, 0x70, 0x6b, 0x67, 0x2f, 0x64, 0x61,
	0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x2f, 0x72, 0x65, 0x64, 0x69, 0x73, 0x2f, 0x72, 0x65, 0x64,
	0x69, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x40, 0x0a, 0x06, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x12, 0x36, 0x0a, 0x06, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x63, 0x6d, 0x64, 0x2e, 0x68, 0x7a, 0x2e, 0x69, 0x6e, 0x74, 0x65,
	0x72, 0x6e, 0x61, 0x6c, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x52, 0x06, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x22, 0xc9, 0x01, 0x0a, 0x06, 0x53,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x41, 0x0a, 0x04, 0x68, 0x74, 0x74, 0x70, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x2d, 0x2e, 0x63, 0x6d, 0x64, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x77,
	0x65, 0x67, 0x6f, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x48, 0x54, 0x54, 0x50, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x52, 0x04, 0x68, 0x74, 0x74, 0x70, 0x12, 0x3e, 0x0a, 0x03, 0x72, 0x70, 0x63, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x63, 0x6d, 0x64, 0x2e, 0x63, 0x6c, 0x6f, 0x75,
	0x64, 0x77, 0x65, 0x67, 0x6f, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e,
	0x61, 0x6c, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x52, 0x50, 0x43, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x52, 0x03, 0x72, 0x70, 0x63, 0x12, 0x3c, 0x0a, 0x08, 0x64, 0x61, 0x74, 0x61,
	0x62, 0x61, 0x73, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x63, 0x6d, 0x64,
	0x2e, 0x68, 0x7a, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2e, 0x63, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x42, 0x61, 0x73, 0x65, 0x52, 0x08, 0x64, 0x61,
	0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x22, 0x6e, 0x0a, 0x08, 0x44, 0x61, 0x74, 0x61, 0x42, 0x61,
	0x73, 0x65, 0x12, 0x30, 0x0a, 0x05, 0x6d, 0x79, 0x73, 0x71, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x70, 0x6b, 0x67, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65,
	0x2e, 0x6d, 0x79, 0x73, 0x71, 0x6c, 0x2e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x05, 0x6d,
	0x79, 0x73, 0x71, 0x6c, 0x12, 0x30, 0x0a, 0x05, 0x72, 0x65, 0x64, 0x69, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x70, 0x6b, 0x67, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61,
	0x73, 0x65, 0x2e, 0x72, 0x65, 0x64, 0x69, 0x73, 0x2e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x05, 0x72, 0x65, 0x64, 0x69, 0x73, 0x42, 0x31, 0x5a, 0x2f, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x77,
	0x65, 0x67, 0x6f, 0x64, 0x65, 0x6d, 0x6f, 0x2f, 0x63, 0x6d, 0x64, 0x2f, 0x63, 0x6c, 0x6f, 0x75,
	0x64, 0x77, 0x65, 0x67, 0x6f, 0x64, 0x65, 0x6d, 0x6f, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e,
	0x61, 0x6c, 0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_cmd_cloudwegodemo_internal_config_config_proto_rawDescOnce sync.Once
	file_cmd_cloudwegodemo_internal_config_config_proto_rawDescData = file_cmd_cloudwegodemo_internal_config_config_proto_rawDesc
)

func file_cmd_cloudwegodemo_internal_config_config_proto_rawDescGZIP() []byte {
	file_cmd_cloudwegodemo_internal_config_config_proto_rawDescOnce.Do(func() {
		file_cmd_cloudwegodemo_internal_config_config_proto_rawDescData = protoimpl.X.CompressGZIP(file_cmd_cloudwegodemo_internal_config_config_proto_rawDescData)
	})
	return file_cmd_cloudwegodemo_internal_config_config_proto_rawDescData
}

var file_cmd_cloudwegodemo_internal_config_config_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_cmd_cloudwegodemo_internal_config_config_proto_goTypes = []interface{}{
	(*Config)(nil),            // 0: cmd.hz.internal.config.Config
	(*Server)(nil),            // 1: cmd.hz.internal.config.Server
	(*DataBase)(nil),          // 2: cmd.hz.internal.config.DataBase
	(*server.HTTPServer)(nil), // 3: cmd.cloudwegodemo.internal.server.HTTPServer
	(*server.RPCServer)(nil),  // 4: cmd.cloudwegodemo.internal.server.RPCServer
	(*mysql.Option)(nil),      // 5: pkg.database.mysql.Option
	(*redis.Option)(nil),      // 6: pkg.database.redis.Option
}
var file_cmd_cloudwegodemo_internal_config_config_proto_depIdxs = []int32{
	1, // 0: cmd.hz.internal.config.Config.server:type_name -> cmd.hz.internal.config.Server
	3, // 1: cmd.hz.internal.config.Server.http:type_name -> cmd.cloudwegodemo.internal.server.HTTPServer
	4, // 2: cmd.hz.internal.config.Server.rpc:type_name -> cmd.cloudwegodemo.internal.server.RPCServer
	2, // 3: cmd.hz.internal.config.Server.database:type_name -> cmd.hz.internal.config.DataBase
	5, // 4: cmd.hz.internal.config.DataBase.mysql:type_name -> pkg.database.mysql.Option
	6, // 5: cmd.hz.internal.config.DataBase.redis:type_name -> pkg.database.redis.Option
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_cmd_cloudwegodemo_internal_config_config_proto_init() }
func file_cmd_cloudwegodemo_internal_config_config_proto_init() {
	if File_cmd_cloudwegodemo_internal_config_config_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cmd_cloudwegodemo_internal_config_config_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Config); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_cloudwegodemo_internal_config_config_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Server); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_cloudwegodemo_internal_config_config_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataBase); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cmd_cloudwegodemo_internal_config_config_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cmd_cloudwegodemo_internal_config_config_proto_goTypes,
		DependencyIndexes: file_cmd_cloudwegodemo_internal_config_config_proto_depIdxs,
		MessageInfos:      file_cmd_cloudwegodemo_internal_config_config_proto_msgTypes,
	}.Build()
	File_cmd_cloudwegodemo_internal_config_config_proto = out.File
	file_cmd_cloudwegodemo_internal_config_config_proto_rawDesc = nil
	file_cmd_cloudwegodemo_internal_config_config_proto_goTypes = nil
	file_cmd_cloudwegodemo_internal_config_config_proto_depIdxs = nil
}
